### PR TITLE
Vadim Kozlov (shikter) homework

### PR DESCRIPTION
**Pull request by shikter**
My first homework.
You will find my idea in "Readme" file.

### CODE REVIEW

**Comment by romilrobtsenkov** [comment]
@shikter the idea is still missing
```PHP
function generateIdea(){

}
```

**Comment by romilrobtsenkov** [comment]
:+1:

**Comment by shikter** [comment]
@romilrobtsenkov 

I am done with the main homework tasks, but I did not find the code about "data request" like - 
`<input type="number" name="date" id="date" style="width: 300px;" placeholder="31.12.2016">`

The type "number" - support only one number, you can't use any other character. How I can do the same thing, but only for the date, like: 31.12.2016 (day.mon.year).

**Comment by romilrobtsenkov** [comment]
`<option selected></option>`

ili

`<option value="notselected" selected>Pick a category</option>`
`<option value="1">test 1</option>`
`<option value="2">test 2</option>`

**Comment by shikter** [comment]
@romilrobtsenkov 

`if(!date){
					error += "<br>Please select date";
					formIsValid = false;
					}else{
					if(preg_match("^[0-3][0-9].[0-1][0-9].[0-9]{4}$",$date)){
						//true
						formIsValid = true;
					}else{
						formIsValid = false;
					}
				}`

Not working with firefox.

`<input type="date" name="date" id="date" style="width: 300px;" placeholder="31.12.2016">`

Trying the command "datetime". But also not working, even in the Chrome.

**Comment by romilrobtsenkov** [comment]
Nice work and really good idea description!
:+1:

**Pull request closed without merging**
